name: Sophos
version: '2.2.8'
authors: [Refrac, AnnaDev]
main: me.refrac.sophos.Sophos
description: Sophos Chat Protection
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  sophos:
    description: Sophos command
  staffchat:
    description: StaffChat command
    aliases: sc
  sctoggle:
    description: StaffChat toggle command
  chat:
    description: Handles muteing or clearing the chat

permissions:
  sophos.silent.join:
    description: Allows the user to join silently
    default: false
  sophos.silent.quit:
    decription: Allows the user to quit silently
    default: false